//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuasociados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases()
        {
            this.States = new HashSet<States>();
        }
    
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdLawyer { get; set; }
        public System.DateTime InitiationDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Lawyers Lawyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<States> States { get; set; }
    }
}
