//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuasociados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        public string Direccion { get; set; }
        public string HorarioAtencion { get; set; }
        public string Tel { get; set; }
        public string Celular { get; set; }
        public string Mail { get; set; }
        public int Id { get; set; }
    }
}
