//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuasociados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int IdLawyer { get; set; }
        public bool Active { get; set; }
    
        public virtual Lawyers Lawyers { get; set; }
    }
}
