//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuasociados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime InitiationDate { get; set; }
        public string Comment { get; set; }
        public int IdCase { get; set; }
    
        public virtual Cases Cases { get; set; }
    }
}
